spring:
    application:
        name: dir-metadata-service
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

    datasource:
        password: root
        username: root
        url: jdbc:mysql://mysql:3306/metadata
    jpa:
        hibernate:
            ddl-auto: update

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
